/**
 * Writes a Prism script that exports every graph of every named document.
 *
 * Prism can be driven from outside - `prism.exe @script.pzc` - and its
 * scripting language has `ExportSVG`. That is the whole reference pipeline: it
 * draws the figure, we compare structure against it, and no one has to put two
 * screenshots side by side again.
 *
 *   node tools/prism-reference/generate.mjs <outputDir> <file...>
 *   "C:/Program Files/GraphPad/Prism/prism.exe" "@<outputDir>/export.pzc"
 *
 * Prism returns immediately and runs invisibly, so wait for `done.txt` in the
 * output directory rather than for the process to exit.
 *
 * The graph count comes from our own reader, because the script has to say
 * `GoTo G, n` for each one and there is no loop over graphs in the language.
 * That is a small circularity worth naming: if we miscount graphs we export
 * the wrong set. It cannot make a wrong chart look right, only make a
 * comparison go missing, and a missing reference is visible.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { basename, resolve } from 'node:path'
import { readProject } from '@prismbinder/model'

const [outDir, ...files] = process.argv.slice(2)

if (outDir === undefined || files.length === 0) {
  console.error('usage: generate.mjs <outputDir> <file...>')
  process.exit(2)
}

const out = resolve(outDir)
mkdirSync(out, { recursive: true })

const lines = [
  '/* Generated by tools/prism-reference/generate.mjs.',
  '   Exports every graph as SVG so our charts can be compared against Prism',
  '   automatically. Run with:  prism.exe @export.pzc                       */',
  `SetPath "${out.replace(/\//g, '\\')}"`,
]

let graphs = 0
for (const file of files) {
  const path = resolve(file)
  let project
  try {
    project = readProject(new Uint8Array(readFileSync(path)), basename(path)).value
  } catch {
    console.error(`skipped ${path}: could not be read`)
    continue
  }
  if (project === undefined) {
    console.error(`skipped ${path}: could not be read`)
    continue
  }

  const sheets = project.sheets.filter((s) => s.kind === 'graph')
  if (sheets.length === 0) continue

  lines.push('', `Open "${path.replace(/\//g, '\\')}"`)
  sheets.forEach((sheet, i) => {
    lines.push(`GoTo G, ${i + 1}`, `ExportSVG "${slug(basename(path))}-g${i + 1}.svg"`)
    graphs++
  })
  lines.push('Close')
}

// The signal the harness waits on. Prism does not block, so there is nothing
// else to wait for.
lines.push('', 'OpenOutput "done.txt"', 'WText "done"', '')

const script = `${out}/export.pzc`
writeFileSync(script, lines.join('\r\n'), 'utf8')
console.log(`${script}\n  ${graphs} graph(s) across ${files.length} document(s)`)
console.log(`  run: "C:/Program Files/GraphPad/Prism/prism.exe" "@${script}"`)
console.log(`  then wait for ${out}/done.txt`)

/** Same shape as the exporter uses, so a reference sits beside its chart. */
function slug(name) {
  return name.replace(/\.[^.]+$/, '').replace(/[^\w .-]+/g, '_')
}
